### PR TITLE
Fix NULL sources at flowsToList 

### PR DESCRIPTION
**Pull request by feliciahalim**
... by adding additional `null` sources checking in the `directLocalFlowSources` and before `addDependency` method being called

This is also a fix for `make test`, with result:
Testing Time: 617.29s
Failing Tests (8):
    KLEE :: Feature/KleeReportError.c
    KLEE :: Feature/MemoryLimit.c
    KLEE :: Feature/OvershiftCheck.c
    KLEE :: Feature/consecutive_divide_by_zero.c
    KLEE :: Runtime/POSIX/DirConsistency.c
    KLEE :: Runtime/POSIX/DirSeek.c
    KLEE :: Runtime/POSIX/SeedAndFail.c
    KLEE :: Runtime/POSIX/Write2.c

  Expected Passes    : 160
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 8

`Previously (master branch) :`
Testing Time: 617.83s
Failing Tests (9):
    KLEE :: Feature/KleeReportError.c
    KLEE :: Feature/MemoryLimit.c
    KLEE :: Feature/OvershiftCheck.c
    KLEE :: Feature/consecutive_divide_by_zero.c
    KLEE :: Runtime/POSIX/DirConsistency.c
    KLEE :: Runtime/POSIX/DirSeek.c
    KLEE :: Runtime/POSIX/Futimesat.c
    KLEE :: Runtime/POSIX/SeedAndFail.c
    KLEE :: Runtime/POSIX/Write2.c

  Expected Passes    : 159
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 9

### CODE REVIEW

**Comment by domainexpert** [comment]
Thank you @feliciahalim . But what are the benchmarks that fail?

**Comment by feliciahalim** [comment]
@domainexpert The benchmark that fails without this fix is `Runtime/POSIX/Futimesat.c`

**Comment by domainexpert** [comment]
Well done @feliciahalim. I have just added small fixes as I noticed the handling of the external functions in `Dependency::execute` is sometimes done incorrectly. Following is the latest result:
```
********************
Testing Time: 606.85s
********************
Failing Tests (4):
    KLEE :: Feature/MemoryLimit.c
    KLEE :: Runtime/POSIX/DirConsistency.c
    KLEE :: Runtime/POSIX/DirSeek.c
    KLEE :: Runtime/POSIX/SeedAndFail.c

  Expected Passes    : 164
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 4
```

**Comment by domainexpert** [comment]
@feliciahalim Just to clarify, what I meant by correcting the semantics of external function calls is the following fixes in the external function handler in Dependency::execute:
1. Fixed an error in the argument index for printf. 
2. Removed the dependency computation for calloc,  as the returned address value should not depend on the arguments (see `man calloc`). 
3. Removed the dependency computation for geteuid as it has no argument. 
I'm happy for this PR to be merged.

**Comment by feliciahalim** [comment]
@domainexpert  Thank you for the fixing.. The execution of `make test `result looks good for me.

**Pull request merged**
