### PR TITLE
Remove element from FlowsToList that already set as core to prevent s…

### PR DESCRIPTION
**Pull request by feliciahalim**
…et the same elements as core multiple times.

This PR does not change the subsumption result of basic examples. It speed up the execution of `scalability/regexp`from 94.23s to 68.97s without changing the subsumption result.

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim It took me a while to figure out why this should be correct, and now I believe your optimization is correct, due to the SSA (static single assignment) form used in LLVM. When a value is marked to be in the core, that also means that that value will never be used again in other branches or execution paths, because all values are only used once in the SSA form. More concretely, when a flows to b, denoted `a -> b`, and `b` is used in a branch condition `c(b)`, which is in the unsatisfiability core, `Dependency::markAllValues` traverses this flow backward to mark the values and allocations. No other paths/branches will ever use `b` other than `c(b)`, and hence it is safe to delete `a->b`, since this flow will never be re-traversed. Other branches will instead perform a load, using `Dependency::storesMap` or `Dependency::storageOfMap` fields to build its own flows-to relation.  

Now:
1. Would you please move the call of to `removeCoreFromFlowsToList` from `markAllValues(AllocationGraph *g, llvm::Value *value)`, to `markAllValues(AllocationGraph *g, VersionedValue *value)`? This is so that we could benefit from more deletions of `flowsToList` elements.
2. Would you please make `removeCoreFromFlowsToList` private?
3. Would you please correctly format of the comment at the callsite of `removeCoreFromFlowsToList`? This can be done by writing the whole comment in one line, save the file, and execute `git clang-format`.

**Comment by domainexpert** [comment]
@feliciahalim Would you please check that `make test` expected results are the same? Thank you.

**Comment by feliciahalim** [comment]
@domainexpert  I have checked the `make test` result by compare the result in the presence of `removeCoreFromFlowsToList()`

When the `removeCoreFromFlowsToList()` is deleted, the result is:
```
Testing Time: 621.01s
Failing Tests (9):
    KLEE :: Feature/KleeReportError.c
    KLEE :: Feature/MemoryLimit.c
    KLEE :: Feature/OvershiftCheck.c
    KLEE :: Feature/consecutive_divide_by_zero.c
    KLEE :: Runtime/POSIX/DirConsistency.c
    KLEE :: Runtime/POSIX/DirSeek.c
    KLEE :: Runtime/POSIX/Futimesat.c
    KLEE :: Runtime/POSIX/SeedAndFail.c
    KLEE :: Runtime/POSIX/Write2.c

  Expected Passes    : 159
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 9

```
In the presence of `removeCoreFromFlowsToList()` , the result is :
```
Testing Time: 1018.04s
Failing Tests (5):
    KLEE :: Feature/KleeReportError.c
    KLEE :: Feature/OvershiftCheck.c
    KLEE :: Feature/consecutive_divide_by_zero.c
    KLEE :: Runtime/POSIX/Futimesat.c
    KLEE :: Runtime/POSIX/SeedAndFail.c

  Expected Passes    : 163
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 5
```

**Comment by domainexpert** [comment]
@feliciahalim I think it may be risky to merge this optimization, although it was an excellent attempt. Perhaps we should first focus on clearing the regression (`make test`) failures, after which, we can use the regression suite to work on performance optimizations to check that the optimizations that we implement do not introduce regression.

**Comment by domainexpert** [comment]
@feliciahalim In this case it wasn't a regression, but improvement in the number of test successes, however, it appears that Tracer-X ran slower with the optimization, and the regression test result changed for unknown reason.

**Comment by domainexpert** [comment]
A mistake in my previous comment where I said that in SSA form, a variable is only used once. This is not true: in SSA, a variable is only **defined** once.

In any case, `Dependency::flowsToList` field no longer exists in the code and hence I close this PR.

**Pull request closed without merging**
