### PR TITLE
Resolve issue#56: Project Subtitle Needs Updating

### PR DESCRIPTION
**Pull request by feliciahalim**
To resolve this issue: https://github.com/feliciahalim/klee/issues/56

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim Thank you! Also if one accessed https://github.com/feliciahalim/klee, one reads "KLEE Symbolic Virtual Machine" with website http://klee.llvm.org above the commit list. Perhaps other subtitle would be better, such as "Tracer-X KLEE Symbolic Virtual Machine" with website http://paella.ddns.comp.nus.edu.sg/tracerx/. Only @feliciahalim has the permission to change this. I'll edit the README.md.

**Comment by domainexpert** [comment]
@feliciahalim I have updated the subttitle to "Tracer-X KLEE Symbolic Virtual Machine" with a link to Tracer-X web page.

**Comment by feliciahalim** [comment]
@domainexpert I have updated the subtitle accordingly.. Thanks

**Comment by domainexpert** [comment]
@feliciahalim Awesome! I'm happy for this to be merged unless you noticed other issues.

**Pull request merged**
