### PR TITLE
Applying Substitution for Further Simplification of Existential Formula Used in Subsumption Check

### PR DESCRIPTION
**Pull request by feliciahalim**
@domainexpert The last result shows the number of subsumption were 2 instead of 4. It seems we able to still get 4 subsumptions by changing 2 things:

1. I noticed in` ITree.cpp `line 1241, there's variable substitution for the `interpolant` and I think it will be useful if we could do the variable substitution to the `equalities` as well. In this case, we can get the opportunity to replace `shadow expression `with its `non shadow expression` that we have obtained from the `substitution mapping`.

2. In the `simplifyArithmeticBody` method, I add one `if` condition that process the `interpolant` that has `existential` variable in it.

I have tested this PR on basic examples and `Regexp`.c, this PR only increase the subsumption rates in addition_safe8. But, it doesn't affect other subsumption rates/error reports.

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim It is very easy to see that no. 2 is very reasonable, however, no. 1 is somewhat incredible, but it is not impossible to be correct. Do you have an example of a query or a set of queries before and after being simplified by no. 1? Let's confirm the logical equivalence of the queries.

Once we confirm that no. 1 is correct based on the examples, I think we should compare the performance on the scalability examples (Regexp.c, bubble9.c, or tr.c and its siblings).

**Comment by feliciahalim** [comment]
@domainexpert  This is one of the query example that can be captured from `addition_safe8`:

From `ref<Expr> equalities = getSubstitution(body->getKid(1), substitution)`, we get the mapping of substitution `[shadow_y = y] `and we also have this `equality`:
```
 (Eq (Add w32 3
              (Add w32 (ReadLSB w32 0 __shadow__x)
                       (ReadLSB w32 0 __shadow__y)))
     (Add w32 2
              (Add w32 (ReadLSB w32 0 x)
                       (ReadLSB w32 0 y))))
```

As we can see, we need to eliminate `shadow_x` and `shadow_y` from expression. We already knew `shadow_y` is equal to `y`.  But master branch does not use this equality` [shadow_y = y]` to help simplify other complicated equality. So the idea is to replace the occurrence of the `shadow_y` first before invoking `simplifyArithmeticBody` method such that the expression become like this:

```
(Eq (Add w32 3
              (Add w32 (ReadLSB w32 0 __shadow__x)
                       N0:(ReadLSB w32 0 y)))
     (Add w32 2
              (Add w32 (ReadLSB w32 0 x)
                       N0)))
```

I just checked `tr_nosyscall`  2 arguments, with both 3 characters long, max-time =  600 seconds. The subsumption rates and error paths are increased. Before the subsumed paths was 167, now 189.  Before the error paths were 32, now 151. But, I will further check the result on other scalability experiments.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! I think you have even inadvertently fixed a bug. Substitution is not only good to be done on the equalities for performance, it also MUST be done on the equalities for correctness. The substitutions are actually equality constraints pulled out from the equalities part of an existentially-quantified formula. Not applying it to the equalities themselves mean losing the constraints forever and therefore weakening the whole formula such that it is no longer logically equivalent to the formula before the simplification. Very well done!

**Comment by domainexpert** [comment]
@feliciahalim I would definitely recommend merging modification no. 1 since it is a bugfix, but modification no. 2 needs further testing on its impact on performance.

**Comment by domainexpert** [comment]
@feliciahalim So the experiment that I think needs to be done now is on comparing the performance before and after commit https://github.com/tracer-x/klee/pull/69/commits/15f1a89684015b05978a1a06250d6c8dceafd1f4

**Comment by feliciahalim** [comment]
@domainexpert I am working on the experiments right now to execute Regexp, tr, tr_nosyscall, and tr_small.

**Comment by feliciahalim** [comment]
@domainexpert  I just made another new commit which check if the substitution candidate has existential before performing substitution mapping, otherwise there will be slowing down especially in `Regexp.c` probably because it attempts to search through the variable for being substitute where it actually doesn't need to be substituted.

This is the details of experiment result:
`Regexp:` The traversed paths profile are the same, but master is slower (194.98s) compared to this PR (181.52s).
`Tr:`All runs reached timeout of 2 minutes. But, there is 3 subsumptions in this PR, while master branch has 1 subsumption. Number of error paths are the same.
`Tr_nosyscall:` The run of 2 symbolic arguments 1 character each, completed for both master and this PR. Tr_nosyscall shows small nondeterminism in the number of subsumed paths or the instructions traversed. For 3 executions, 2 executions don't have any subsumption, but the last execution has 1 subsumption. Reported error paths are the same. The average time for both master and PR are similar, 1 minutes 14s.
TR_small: The run of 2 symbolic arguments 1 character each, completed for both master and this PR. Both master and PR have the same number of subsumptions, reported error paths, and similar execution time (1m 12s).

**Pull request merged**
