### PR TITLE
WIP: Weakest Precondition

### PR DESCRIPTION
**Pull request by rasoolmaghareh**

### CODE REVIEW

**Comment by domainexpert** [comment]
@rasoolmaghareh Discussions in #74 and #211 may be useful.

**Comment by rasoolmaghareh** [comment]
Will follow them, thank you very much.

**Comment by domainexpert** [comment]
@rasoolmaghareh I forgot to mention that #43 may be relevant to this work as well. Once this PR is merged, we can close #43.

**Comment by rasoolmaghareh** [comment]
Thank you very much. It was quite a useful discussion and I will try to see if can reuse part of the code in the branch.

**Comment by rasoolmaghareh** [comment]
There are two issues in the current implementation:

1- Assuming a if-statement with the guard "b", if the false branch is feasible, the expression which should be collected by the weakest precondition is "not(b)". However, the current implementation stores "b".

2- In the function WeakestPreCondition::markVariables it is observed that sometimes the order of instructions is incorrect. As a result the marking of the instructions is performed incorrectly.

**Comment by rasoolmaghareh** [comment]
Add the current stage we decided to redesign some parts of the code. 

The first change that we are planning is to generate the WP expression not only for a univarient target (count/resource variable `kappa` or `wcet`) but also for all targets and the infeasible paths too. 

As a result we need a general method to write `pre` function which computes a `wp_pre` expression from a transition `tr` and a weakest precondition expression `wp`: 

`wp_pre`
|
| `tr`
v
`wp`

Both `wp` and `wp_pre` will contain only memory addresses in their expressions and not registers. 

The `pre` function will create temporary memory addresses for registers in the instructions and reclaim them when `wp_pre` is generated. For example consider the following transition and WP expression:

| `%1 = Load %a`
| `%inc = Add %1 , 1`
| `Store %inc , %a`
v
`a < 5`

The `pre` function will generate `wp_pre` in the following steps:
`a < 4` 
| `%1 = Load %a`
  `%1 + 1 < 5` =>   `%1 < 4`
| `%inc = Add %1 , 1`
  `%inc < 5`
| `Store %inc , %a`
v
`a < 5`

**Comment by rasoolmaghareh** [comment]
The decision made is that the partitioning should be done based on whether an expression has relationship with the branchCondition or not. In the end we would have two partitions were we will perform intersection in one partition and marking on the partition related to the branchCondition.

**Comment by xuanlinhha** [comment]
TxWeakestPreCondition::intersectExpr(ref<Expr> branchCondition, std::vector<ref<Expr> > expr1, std::vector<ref<Expr> > expr2)
This function produces 3 partitions as follow:
1. w1r ^ w2r
2. w1b ^ b
3. w2b ^ !b
Then merge 2 partitions 2 and 3 if possible

**Comment by rasoolmaghareh** [comment]
Current unresolved issues:
1- The program variables added to the WP Expr are 32 bit while in reality they might be different. This can cause crash.
2- The `TxWeakestPreCondition::updateSubsumptionTableEntry` function seems to be updating the concretelyAddressedStore component incorrectly.

**Pull request merged**
