### PR TITLE
ICMP/atomic condition coverage

### PR DESCRIPTION
**Pull request by sanghu1790**
Adding one feature of ICMP/atomic condition coverage, it is useful while comparing coverage with CBMC.

### CODE REVIEW

**Comment by sanghu1790** [comment]
********************
Testing Time: 59.90s
********************
Failing Tests (2):
    KLEE :: Feature/Realloc.c
    KLEE :: Feature/const_array_opt1.c  Expected Passes    : 179
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 2
Makefile:49: recipe for target 'check-local' failed
make[1]: *** [check-local] Error 1
make[1]: Leaving directory '/home/sanghu/TracerX/tracerx/test'
/home/sanghu/TracerX/tracerx/Makefile.rules:1863: recipe for target 'check' failed
make: *** [check] Error 2
sanghu@paella2018:~/TracerX/tracerx$

**Comment by rasoolmaghareh** [comment]
@sanghu1790 the time is very slow. We usually finish this in 13 to 16 seconds.

May I ask if you were running anything else on your machine?

**Comment by sanghu1790** [comment]
@rasoolmaghareh No, I wasn't running any other application other than browser. Still, I rebooted machine and reran the time is still 58 sec. Also, I checked with master branch the time is same.  Is there any issue?

**Comment by rasoolmaghareh** [comment]
ok, I think your machine is slower since on TracerX server the time is usually 13-16 seconds.

**Comment by sanghu1790** [comment]
Noted @rasoolmaghareh

**Comment by rasoolmaghareh** [comment]
On my machine, the time is correct:

```
********************
Testing Time: 14.22s
********************
Failing Tests (2):
    KLEE :: Feature/Realloc.c
    KLEE :: Feature/const_array_opt1.c

  Expected Passes    : 179
  Expected Failures  : 2
  Unsupported Tests  : 2
  Unexpected Failures: 2
```

**Comment by rasoolmaghareh** [comment]
`make` in the `klee-examples\basic` also passed:
```
make[2]: Leaving directory '/home/sajjad/Tracer-X/klee-examples/basic'
make[1]: Leaving directory '/home/sajjad/Tracer-X/klee-examples/basic'
for KTEST in pointer_wp5.tx/*.ktest ; do \
	( ( /usr/local/lib/tracerx/bin/ktest-tool --write-ints $KTEST ) >> pointer_wp5.inputs ) ; \
done
```

**Comment by rasoolmaghareh** [comment]
Merged into master brach.

**Pull request merged**
